### ISSUE TITLE
The workflow screen does not display properly

### ISSUE THREAD

**Issue by ai-meat** [chrisgoringe/cg-use-everywhere#247]
There is a conflict between the “Anything Everywhere” node and the new version of comfyui, which causes the workflow not to be loaded properly, the interface not to be displayed properly, and the new workflow not to be loaded properly. However, the backend with the node does not report errors and executes normally.

**Comment by 0xBeFa** [comment]
I have the same issue. My console show this error messages:
`api.ts:56 Running on 127.0.0.1:8188
logging.ts:333 ComfyUI Front-end version: 1.3.44
extensionStore.ts:45 Extension pysssss.SnapToGrid is disabled.
extensionStore.ts:45 Extension pysssss.Locking is disabled.
:8188/extensions/dzNodes/dz_DZ_widgets.js:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
app.ts:1700 Error loading extension /extensions/dzNodes/dz_debug.js TypeError: Failed to fetch dynamically imported module: http://127.0.0.1:8188/extensions/dzNodes/dz_debug.js
(anonymous) @ app.ts:1700
imageFeed.js:87 [mtb] - Aborting the loading of mtb's imageFeed in favor of pysssss.ImageFeed
init @ imageFeed.js:87
:8188/api/DZ/debug:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
app.ts:436 Error calling extension 'DZ.widgets' method 'init' Object Object Object
(anonymous) @ app.ts:436
components-manager.js:769 Empty components: policy ignored
:8188/api/pysssss/autocomplete:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
:8188/extensions/ComfyUI-Custom-Scripts/js/assets/favicon-active.user.ico:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
:8188/api/DZ/debug:1 
        
        
       Failed to load resource: the server responded with a status of 405 (Method Not Allowed)
:8188/extensions/ComfyUI-Custom-Scripts/js/assets/favicon.user.ico:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
litegraph.es.js:1583 Uncaught TypeError: Cannot read private member #boundingRect from an object whose class did not declare it
    at Proxy.updateArea (litegraph.es.js:1583:25)
    at LGraphCanvas.computeVisibleNodes (litegraph.es.js:5606:13)
    at LGraphCanvas.computeVisibleNodes (domWidget.ts:258:44)
    at LGraphCanvas.computeVisibleNodes (jsnodes.js:346:64)
    at LGraphCanvas.draw (litegraph.es.js:5622:12)
    at LGraphCanvas.draw (extensions-Cii5QAc-.js:1:124690)
    at LGraphCanvas.renderFrame (litegraph.es.js:4147:14)
litegraph.es.js:1583 Uncaught TypeError: Cannot read private member #boundingRect from an object whose class did not declare it
    at Proxy.updateArea (litegraph.es.js:1583:25)
    at LGraphCanvas.computeVisibleNodes (litegraph.es.js:5606:13)
    at LGraphCanvas.computeVisibleNodes (domWidget.ts:258:44)
    at LGraphCanvas.computeVisibleNodes (jsnodes.js:346:64)
    at LGraphCanvas.draw (litegraph.es.js:5622:12)
    at LGraphCanvas.draw (extensions-Cii5QAc-.js:1:124690)
    at ComfyApp.resizeCanvas (app.ts:1899:18)
    at app.ts:1832:50
litegraph.es.js:1583 Uncaught TypeError: Cannot read private member #boundingRect from an object whose class did not declare it
    at Proxy.updateArea (litegraph.es.js:1583:25)
    at LGraphCanvas.computeVisibleNodes (litegraph.es.js:5606:13)
    at LGraphCanvas.computeVisibleNodes (domWidget.ts:258:44)
    at LGraphCanvas.computeVisibleNodes (jsnodes.js:346:64)
    at LGraphCanvas.draw (litegraph.es.js:5622:12)
    at LGraphCanvas.draw (extensions-Cii5QAc-.js:1:124690)
    at ComfyApp.resizeCanvas (app.ts:1899:18)
    at ResizeObserver.<anonymous> (app.ts:1833:46)
`

**Comment by chrisgoringe** [comment]
Thanks. I’ll investigate.

**Comment by lucabaronti** [comment]
I also have this problem. The behavior is exactly the one described [here](https://github.com/comfyanonymous/ComfyUI/issues/5742).

It took me a while to identify the problem (that's actually comfyui fault, for not giving us much indication on what went wrong in loading the workflow).

**Comment by chrisgoringe** [comment]
@lucabaronti @0xBeFa @ai-meat - Can you check that you have the latest version of UE? There's a version number in the `__init__.py` file. Current version is 5.0.6, anything before 5.0.4 is definitely broken.

**Comment by lucabaronti** [comment]
I relied to ComfyUI manager to keep all my nodes updated, but you are right for some reason it didn't updated the node (the branch was detached too).
I updated it manually to 5.0.6 and now everything works again. Thanks.

**Comment by isketch93** [comment]
I'm sad to report that version 5.0.6 does not solve the issue for me. I know this is the only problematic node because disabling it alone fixes the issue completely.

In my case, the Manager _did_  update UE by itself. Just to be sure I also tried reinstalling the node from scratch and manually forcing an update with `git pull`.
Sadly, the former changed nothing, and the latter returned `Already up to date.`, also solving nothing.

**Comment by chrisgoringe** [comment]
Thanks. There must be a conflict with another node, since not everyone has
the problem. Are you able to post a list of custom nodes you have installed?

**Comment by isketch93** [comment]
Your response prompted me to try leaving UE enabled and disabling/re-enabling every other node, to try and identify a specific conflict. I was not able to pinpoint any node that, once disabled, let UE work properly.

In a last ditch attempt, i disabled every custom node, including the Manager, _except_ UE, no dice.
I also tried the same, but leaving tha Manager enabled too, nothing again.

Anyway, this is the custom nodes loading part of the log:

> Import times for custom nodes:
> [2024-11-25 10:03:08.418]    0.0 seconds: /ComfyUI/custom_nodes/quick-connections
> [2024-11-25 10:03:08.419]    0.0 seconds: /ComfyUI/custom_nodes/websocket_image_save.py
> [2024-11-25 10:03:08.419]    0.0 seconds: /ComfyUI/custom_nodes/SDXLAspectRatio.py
> [2024-11-25 10:03:08.421]    0.0 seconds: /ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus
> [2024-11-25 10:03:08.421]    0.0 seconds: /ComfyUI/custom_nodes/attention-couple-ComfyUI
> [2024-11-25 10:03:08.422]    0.0 seconds: /ComfyUI/custom_nodes/efficiency-nodes-comfyui
> [2024-11-25 10:03:08.422]    0.0 seconds: /ComfyUI/custom_nodes/comfyui_easy_padding
> [2024-11-25 10:03:08.423] [Impact Pack] Wildcards loading done.
> [2024-11-25 10:03:08.423]    0.0 seconds: /ComfyUI/custom_nodes/ComfyUI-IC-Light-Native
> [2024-11-25 10:03:08.423]    0.0 seconds: /ComfyUI/custom_nodes/ComfyUI-ComfyCouple
> [2024-11-25 10:03:08.423]    0.0 seconds: /ComfyUI/custom_nodes/ComfyUI-Eagle-PNGInfo
> [2024-11-25 10:03:08.423]    0.0 seconds: /ComfyUI/custom_nodes/comfy-image-saver
> [2024-11-25 10:03:08.423]    0.0 seconds: /ComfyUI/custom_nodes/sigmas_tools_and_the_golden_scheduler
> [2024-11-25 10:03:08.423]    0.0 seconds: /ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite
> [2024-11-25 10:03:08.423]    0.0 seconds: /ComfyUI/custom_nodes/ComfyUI-WD14-Tagger
> [2024-11-25 10:03:08.424]    0.0 seconds: /ComfyUI/custom_nodes/masquerade-nodes-comfyui
> [2024-11-25 10:03:08.424]    0.0 seconds: /ComfyUI/custom_nodes/ComfyUI-eesahesNodes
> [2024-11-25 10:03:08.424]    0.0 seconds: /ComfyUI/custom_nodes/sdxl_utility.py
> [2024-11-25 10:03:08.424]    0.0 seconds: /ComfyUI/custom_nodes/comfyui_controlnet_aux
> [2024-11-25 10:03:08.424]    0.0 seconds: /ComfyUI/custom_nodes/ComfyUI-IC-Light
> [2024-11-25 10:03:08.424]    0.0 seconds: /ComfyUI/custom_nodes/ComfyUI-AutomaticCFG
> [2024-11-25 10:03:08.424]    0.0 seconds: /ComfyUI/custom_nodes/ComfyUI-GlifNodes
> [2024-11-25 10:03:08.424]    0.0 seconds: /ComfyUI/custom_nodes/ControlAltAI-Nodes
> [2024-11-25 10:03:08.424]    0.0 seconds: /ComfyUI/custom_nodes/comfyui-inpaint-nodes
> [2024-11-25 10:03:08.424]    0.0 seconds: /ComfyUI/custom_nodes/ComfyUI-Flowty-LDSR
> [2024-11-25 10:03:08.424]    0.0 seconds: /ComfyUI/custom_nodes/comfyui-ultralytics-yolo
> [2024-11-25 10:03:08.424]    0.0 seconds: /ComfyUI/custom_nodes/ComfyUI-Custom-Scripts
> [2024-11-25 10:03:08.424]    0.0 seconds: /ComfyUI/custom_nodes/ComfyUI-DDColor
> [2024-11-25 10:03:08.424]    0.0 seconds: /ComfyUI/custom_nodes/comfyui-animatediff
> [2024-11-25 10:03:08.424]    0.0 seconds: /ComfyUI/custom_nodes/ComfyUI_JPS-Nodes
> [2024-11-25 10:03:08.424]    0.0 seconds: /ComfyUI/custom_nodes/comfyui-various
> [2024-11-25 10:03:08.424]    0.0 seconds: /ComfyUI/custom_nodes/ComfyUI-AdvancedLivePortrait
> [2024-11-25 10:03:08.424]    0.0 seconds: /ComfyUI/custom_nodes/ComfyUI_essentials
> [2024-11-25 10:03:08.424]    0.0 seconds: /ComfyUI/custom_nodes/ModelUnloader
> [2024-11-25 10:03:08.424]    0.0 seconds: /ComfyUI/custom_nodes/ComfyUI-Frame-Interpolation
> [2024-11-25 10:03:08.424]    0.0 seconds: /ComfyUI/custom_nodes/ComfyUI-Impact-Pack
> [2024-11-25 10:03:08.424]    0.0 seconds: /ComfyUI/custom_nodes/Derfuu_ComfyUI_ModdedNodes
> [2024-11-25 10:03:08.424]    0.0 seconds: /ComfyUI/custom_nodes/rgthree-comfy
> [2024-11-25 10:03:08.424]    0.0 seconds: /ComfyUI/custom_nodes/ComfyUI-CogVideoXWrapper
> [2024-11-25 10:03:08.424]    0.0 seconds: /ComfyUI/custom_nodes/CogVideoX-Fun
> [2024-11-25 10:03:08.424]    0.0 seconds: /ComfyUI/custom_nodes/ComfyUI_ExtraModels
> [2024-11-25 10:03:08.424]    0.0 seconds: /ComfyUI/custom_nodes/ComfyUI-GGUF
> [2024-11-25 10:03:08.424]    0.0 seconds: /ComfyUI/custom_nodes/ComfyUI_NYJY
> [2024-11-25 10:03:08.425]    0.0 seconds: /ComfyUI/custom_nodes/comfyui-prompt-reader-node
> [2024-11-25 10:03:08.425]    0.0 seconds: /ComfyUI/custom_nodes/ComfyUI_Comfyroll_CustomNodes
> [2024-11-25 10:03:08.425]    0.0 seconds: /ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved
> [2024-11-25 10:03:08.425]    0.0 seconds: /ComfyUI/custom_nodes/ComfyUI-Crystools
> [2024-11-25 10:03:08.425]    0.0 seconds: /ComfyUI/custom_nodes/comfyui-reactor-node
> [2024-11-25 10:03:08.425]    0.0 seconds: /ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale
> [2024-11-25 10:03:08.425]    0.0 seconds: /ComfyUI/custom_nodes/ComfyUI-Manager
> [2024-11-25 10:03:08.425]    0.0 seconds: /ComfyUI/custom_nodes/ComfyUI-segment-anything-2
> [2024-11-25 10:03:08.425]    0.0 seconds: /ComfyUI/custom_nodes/ComfyUI-Florence2
> [2024-11-25 10:03:08.425]    0.0 seconds: /ComfyUI/custom_nodes/ComfyUI-Login
> [2024-11-25 10:03:08.425]    0.0 seconds: /ComfyUI/custom_nodes/ComfyUI_InstantIR_Wrapper
> [2024-11-25 10:03:08.425]    0.0 seconds: /ComfyUI/custom_nodes/ComfyUI-Easy-Use
> [2024-11-25 10:03:08.425]    0.1 seconds: /ComfyUI/custom_nodes/ComfyUI_bitsandbytes_NF4
> [2024-11-25 10:03:08.425]    0.1 seconds: /ComfyUI/custom_nodes/ComfyUI-PuLID-Flux
> [2024-11-25 10:03:08.425]    0.1 seconds: /ComfyUI/custom_nodes/comfyui_segment_anything
> [2024-11-25 10:03:08.425]    0.1 seconds: /ComfyUI/custom_nodes/ComfyUI-ControlnetAux
> [2024-11-25 10:03:08.425]    0.1 seconds: /ComfyUI/custom_nodes/ComfyUI_LayerStyle
> [2024-11-25 10:03:08.425]    0.1 seconds: /ComfyUI/custom_nodes/comfyui-art-venture
> [2024-11-25 10:03:08.425]    0.1 seconds: /ComfyUI/custom_nodes/ComfyUI_MileHighStyler
> [2024-11-25 10:03:08.425]    0.1 seconds: /ComfyUI/custom_nodes/ComfyUI-KJNodes
> [2024-11-25 10:03:08.425]    0.3 seconds: /ComfyUI/custom_nodes/PuLID_ComfyUI
> [2024-11-25 10:03:08.425]    0.3 seconds: /ComfyUI/custom_nodes/ComfyUI-CogVideoX-MZ
> [2024-11-25 10:03:08.425]    0.3 seconds: /ComfyUI/custom_nodes/ComfyUI-Depth-Pro
> [2024-11-25 10:03:08.425]    0.4 seconds: /ComfyUI/custom_nodes/ComfyUI-SUPIR
> [2024-11-25 10:03:08.425]    0.5 seconds: /ComfyUI/custom_nodes/ComfyUI_Fill-Nodes
> [2024-11-25 10:03:08.425]    0.8 seconds: /ComfyUI/custom_nodes/ComfyUI_InstantID
> [2024-11-25 10:03:08.425]    1.5 seconds: /ComfyUI/custom_nodes/was-node-suite-comfyui
> [2024-11-25 10:03:08.425]    2.9 seconds: /ComfyUI/custom_nodes/ComfyUI-N-Nodes
> [2024-11-25 10:03:08.425] 
> [2024-11-25 10:03:08.438] Starting server

Should it be useful, I could provide the full log too.
