### ISSUE TITLE
Anything Everywhere freeze

### ISSUE THREAD

**Issue by Chengym2023** [chrisgoringe/cg-use-everywhere#248]
Anything Everywhere freeze workflow in new comfyui version 0.3.3

**Comment by mofos** [comment]
The same issue here, can't load workflows, if done it would freeze up. it was a pain to troubleshoot and find this node which was causing these issues.

**Comment by chrisgoringe** [comment]
Would be helpful if you posted a workflow for which you have the problem

**Comment by zhuliyi0** [comment]
Thanks for the handy node. I have the same issue after upgrading comfyUI to the newest version. It's not workflow-specify. This custom node freezes up the workflow canvas. The issue is gone after I disable this custom node. 



> Would be helpful if you posted a workflow for which you have the problem

**Comment by chrisgoringe** [comment]
I'm using Comfy 0.3.14 and frontend 1.8.14, and it's working for me.

Could you please post the versions of Comfy and Frontend for which it is not working (in the settings menu, go to about).

Also, please press f12 and see if there are any errors in the javascript console.

It's *probably* a conflict with another node and UE.

**Comment by zhuliyi0** [comment]
I am using the same version of Comfy and frontend as you. I disabled all other nodes and only have Anywhere in Custom Node folder. Once I add this node the canvas freezes and the following error pops:

index-DqqhYDnY.js:57220 Uncaught TypeError: Cannot read private member #boundingRect from an object whose class did not declare it
    at Proxy.updateArea (index-DqqhYDnY.js:57220:25)
    at LGraphCanvas.computeVisibleNodes (index-DqqhYDnY.js:61780:14)
    at LGraphCanvas.computeVisibleNodes (index-DqqhYDnY.js:191949:44)
    at LGraphCanvas.draw (index-DqqhYDnY.js:61796:12)
    at LGraphCanvas.renderFrame (index-DqqhYDnY.js:60093:14)

F

[127.0.0.1-1739504826673.log](https://github.com/user-attachments/files/18793153/127.0.0.1-1739504826673.log)

ull log attached.

**Comment by chrisgoringe** [comment]
Thanks. I think I've seen this before and believed it to be fixed. Can you check if your version of UE the latest? Look at `custom_nodes/cg-use-everywhere/__init__.py` - the latest version has `UE_VERSION = "5.0.7"`

**Comment by zhuliyi0** [comment]
Yes you are right, turns out I am running an older version of UE. Comfy Manager somehow did not update it correctly. I manually cloned this repo and the issue is gone. Thanks for your time and have a nice day!

**Comment by chrisgoringe** [comment]
That's great. Comfy Manager has failed to update it for a couple of people.
