### ISSUE TITLE
Problem after Update

### ISSUE THREAD

**Issue by trashie65** [chrisgoringe/cg-use-everywhere#38]
My workflow as all working ok till after installing Anything Everywherenow i get the following error:
All connections seem to be working is visability
No errors in F12

Failed to validate prompt for output 1247:
Output will be ignored
Failed to validate prompt for output 1243:
Output will be ignored
Failed to validate prompt for output 508:
Output will be ignored
Failed to validate prompt for output 1257:
Output will be ignored
Failed to validate prompt for output 510:
Output will be ignored
Failed to validate prompt for output 1255:
Output will be ignored
Failed to validate prompt for output 1242:
Output will be ignored
Failed to validate prompt for output 1256:
Output will be ignored
Failed to validate prompt for output 1245:
Output will be ignored
Failed to validate prompt for output 1244:
Output will be ignored
Failed to validate prompt for output 1246:
Output will be ignored
Failed to validate prompt for output 1355:
Output will be ignored
Exception in thread Thread-5 (prompt_worker):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "D:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\main.py", line 95, in prompt_worker
    e.execute(item[2], prompt_id, item[3], item[4])
  File "D:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 370, in execute
    to_execute = sorted(list(map(lambda a: (len(recursive_will_execute(prompt, self.outputs, a[-1])), a[-1]), to_execute)))
  File "D:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 370, in <lambda>
    to_execute = sorted(list(map(lambda a: (len(recursive_will_execute(prompt, self.outputs, a[-1])), a[-1]), to_execute)))
  File "D:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 210, in recursive_will_execute
    will_execute += recursive_will_execute(prompt, outputs, input_unique_id)
  File "D:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 210, in recursive_will_execute
    will_execute += recursive_will_execute(prompt, outputs, input_unique_id)
  File "D:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 210, in recursive_will_execute
    will_execute += recursive_will_execute(prompt, outputs, input_unique_id)
  [Previous line repeated 990 more times]
  File "D:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 206, in recursive_will_execute
    if isinstance(input_data, list):
RecursionError: maximum recursion depth exceeded while calling a Python object
![Untitled-6](https://github.com/chrisgoringe/cg-use-everywhere/assets/45748708/6d4cc44f-ba39-47a8-8c6b-424359873403)

**Comment by chrisgoringe** [comment]
You've got a loop somehow - I'm actually working on code to catch that right now. But if you post the workflow I'll look for the issue (and use it to test what I'm working on!)

This danger is mentioned [here](https://github.com/chrisgoringe/cg-use-everywhere#cautions)

**Comment by trashie65** [comment]
here is the problem workflow
[PROBLEM AGAIN workflow.txt](https://github.com/chrisgoringe/cg-use-everywhere/files/12876181/PROBLEM.AGAIN.workflow.txt)

**Comment by trashie65** [comment]
OK found the loop, it was the model from the LoRA stack, now all working
