### ISSUE TITLE
Loop (456,504,505,480,481,357,425,427,429) with broadcast (503) - not submitting workflow

### ISSUE THREAD

**Issue by sunny-token** [chrisgoringe/cg-use-everywhere#87]
日志报错：
Error
Loop Detected 456,504,505,480,481,357,425,427,429, 503
Error: Loop Detected 456,504,505,480,481,357,425,427,429, 503
at analyse_graph (http://127.0.0.1:8081/extensions/cg-use-everywhere/use_everywhere.js:73:19)
at async ComfyApp.queuePrompt (http://127.0.0.1:8081/scripts/app.js:1859:16)
浏览器显示
Loop (456,504,505,480,481,357,425,427,429) with broadcast (503) - not submitting workflow

**Comment by hiowenluke** [comment]
@sunny-token :

How did you resolved it?
